In [1]:
import numpy as np

In [2]:
#1 D Array
a = np.array([1,2,3])

In [3]:
a.shape

(3,)

In [4]:
b = np.array([(1,2,3),(4,5,6)])

In [5]:
b.shape

(2, 3)

In [6]:
c = np.random.rand(8,8)

In [7]:
c.shape

(8, 8)

In [8]:
c.size

64

In [9]:
d = c.reshape(64,)

In [10]:
print(d.shape)
print(d)

(64,)
[0.61036564 0.28323583 0.45879831 0.61777901 0.22179757 0.84922656
 0.68348314 0.64643116 0.33538191 0.62353624 0.36405701 0.73396925
 0.53008665 0.60315575 0.4986723  0.44202496 0.37312388 0.22248423
 0.64087137 0.54936496 0.68152606 0.72384086 0.87843437 0.65170049
 0.23445353 0.02967224 0.81036076 0.96268329 0.00248849 0.56806864
 0.77438717 0.03235698 0.76768832 0.03708743 0.41636221 0.33394669
 0.08792631 0.79292359 0.42451053 0.60922714 0.17717659 0.65442578
 0.70336398 0.84342077 0.34707561 0.8688759  0.81693061 0.88888479
 0.55177192 0.39530413 0.55836136 0.4038615  0.99662504 0.33177896
 0.61139612 0.09910437 0.59208967 0.71441801 0.33126337 0.38874339
 0.37910488 0.75596499 0.62379492 0.07976452]


In [11]:
d.dtype

dtype('float64')

In [12]:
np.zeros(1)

array([0.])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.randn(8,8)

array([[ 1.28683173, -0.37186946, -0.25396728,  1.09893981,  0.95138105,
         0.20954999, -0.13693035,  1.87351643],
       [-0.01118741, -0.60575728,  0.95242886, -0.23286562, -1.24427714,
         0.37923167, -1.0298164 ,  0.80181097],
       [-0.42642238,  0.08691739, -0.12580413,  0.0909106 , -1.39262552,
         0.78473531, -0.26113851, -0.37193118],
       [-0.37245022,  0.20512935, -1.44766737, -0.22238054,  0.35638305,
         0.5565921 ,  0.07375626, -2.79121997],
       [ 2.08313774,  0.99618724, -0.23648195,  0.48568578, -0.02799254,
         1.49209525,  0.46184977,  0.69924907],
       [-0.2379893 , -0.78314137,  1.84378287, -0.44875784, -0.53344908,
        -0.76228591, -2.09727782, -1.64423469],
       [-0.51613004, -0.43985693, -0.14243894, -1.25085743,  1.24776644,
         0.96126622, -0.95283443,  0.33750838],
       [ 0.08791821,  0.90191944,  0.40024665,  1.0435782 , -1.51804527,
         0.52369177, -0.76389583,  0.32253569]])

In [15]:
e = np.random.randint(40, size=(8,8))

In [16]:
e

array([[19,  9, 17, 16, 30, 12, 23, 16],
       [ 4,  1, 27, 22,  4, 22, 15,  8],
       [17, 38, 19,  4, 13, 36, 35, 32],
       [ 0, 30, 18, 35, 21, 33, 12,  2],
       [29, 24, 31, 15, 33, 33, 31,  0],
       [15, 10, 19,  3, 21, 23, 19, 12],
       [30, 17, 36, 32, 18,  1, 37, 31],
       [ 7,  9, 37, 15, 32,  8, 30, 36]])

In [17]:
e.shape

(8, 8)

In [18]:
f = e.reshape(64)

In [19]:
f.shape

(64,)

In [20]:
e.T  #Transpose of the matrix

array([[19,  4, 17,  0, 29, 15, 30,  7],
       [ 9,  1, 38, 30, 24, 10, 17,  9],
       [17, 27, 19, 18, 31, 19, 36, 37],
       [16, 22,  4, 35, 15,  3, 32, 15],
       [30,  4, 13, 21, 33, 21, 18, 32],
       [12, 22, 36, 33, 33, 23,  1,  8],
       [23, 15, 35, 12, 31, 19, 37, 30],
       [16,  8, 32,  2,  0, 12, 31, 36]])

In [21]:
f = f.reshape(4,4,4)

In [22]:
f.shape

(4, 4, 4)

In [23]:
f

array([[[19,  9, 17, 16],
        [30, 12, 23, 16],
        [ 4,  1, 27, 22],
        [ 4, 22, 15,  8]],

       [[17, 38, 19,  4],
        [13, 36, 35, 32],
        [ 0, 30, 18, 35],
        [21, 33, 12,  2]],

       [[29, 24, 31, 15],
        [33, 33, 31,  0],
        [15, 10, 19,  3],
        [21, 23, 19, 12]],

       [[30, 17, 36, 32],
        [18,  1, 37, 31],
        [ 7,  9, 37, 15],
        [32,  8, 30, 36]]])

In [24]:
g = np.random.randint(16, size=(8,8))

In [25]:
g.shape
print(g)

[[ 6  7 12  9 14  6  0  4]
 [ 0 10  7  6  2  4  7 14]
 [ 5  4  3  3  6  3 11 11]
 [ 1 10 14 10  3  9  8  2]
 [ 0 10 15  2  1  2  1 14]
 [ 1 10 11  0  8  7 13 11]
 [ 7 14  1  1  8  7 13 12]
 [10  7 15  6 13  8 11 13]]


In [26]:
g.resize(10,10)

In [27]:
g.shape

(10, 10)

In [28]:
g

array([[ 6,  7, 12,  9, 14,  6,  0,  4,  0, 10],
       [ 7,  6,  2,  4,  7, 14,  5,  4,  3,  3],
       [ 6,  3, 11, 11,  1, 10, 14, 10,  3,  9],
       [ 8,  2,  0, 10, 15,  2,  1,  2,  1, 14],
       [ 1, 10, 11,  0,  8,  7, 13, 11,  7, 14],
       [ 1,  1,  8,  7, 13, 12, 10,  7, 15,  6],
       [13,  8, 11, 13,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [29]:
g.resize(4,4)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [ ]:
g[5]

In [ ]:
g[3,2] = 30

In [ ]:
g

In [ ]:
g[1:4,4]

In [ ]:
e.shape

In [ ]:
#Scalar Math
np.add(g,100)

In [ ]:
np.subtract(g,100)

In [ ]:
np.multiply(g,100)

In [ ]:
np.power(g,2)

In [ ]:
#Vector Math
np.add(g,e)

In [ ]:
np.multiply(g,e)

In [ ]:
np.divide(g,e)

In [ ]:
np.mean(g, axis=0)

In [ ]:
np.mean(g)

In [ ]:
np.mean(g,axis=1)

In [ ]:
g.max(axis=0)

In [ ]:
g.max(axis=1)

In [ ]:
g.max()

In [ ]:
g.sum()

In [ ]:
g.sum(axis=0)